# Generated by Django 5.0.6 on 2025-01-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
    ]
