# Generated by Django 5.0.6 on 2024-08-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(default='imagen', upload_to='imagenes/'),
        ),
    ]
